//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<decimal> PrecioTotalPedido { get; set; }
        public Nullable<int> CantidadPedido { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
